-- generated by csdl-to-sql for target h2 from mbttutorial.csdl.xml

create sequence "mbttutorial_xs_data_metrics_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mbttutorial_xs_data_metrics_1_0"
(
    "id" bigint not null,
    "start" timestamp not null,
    "period" decimal(20,6) not null,
    "process" varchar(400) not null,
    "tenant" varchar(800) null,
    "provider" varchar(400) not null,
    "component" varchar(800) not null,
    "metric" varchar(400) not null,
    "unit" varchar(200) not null,
    "count" bigint null,
    "sum" bigint null,
    "average" decimal(25,2) null,
    "minimum" bigint null,
    "maximum" bigint null,
    primary key ("id")
);

create sequence "mbttutorial_Customers_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mbttutorial_Customers_1_0"
(
    "CustomerID" bigint not null,
    "Name" varchar(400) not null,
    "HomeAddress" varchar(400) not null,
    "WorkAddress" varchar(400) null,
    "PlaceOfWork" varchar(400) not null,
    "DateOfBirth" date not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("CustomerID")
);

create index "mbttutorial_Customers_1_0_last_modified_index" on "mbttutorial_Customers_1_0" ("last_modified", "is_deleted");

create table "mbttutorial_Users_1_0"
(
    "UserID" bigint not null,
    "Name" varchar(400) not null,
    "Email" varchar(400) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("UserID")
);

create index "mbttutorial_Users_1_0_last_modified_index" on "mbttutorial_Users_1_0" ("last_modified", "is_deleted");

create table "mbttutorial_xs_repeatability_log_1_0"
(
    "CreationTime" timestamp not null,
    "ResponseStatus" smallint not null,
    "ClientID" varbinary(100) not null,
    "RequestID" varbinary(100) not null,
    "ContentID" varbinary(100) not null,
    "ResponseHeaders" varchar(4000) not null,
    "ResponseData1" varbinary(2000) null,
    "ResponseData2" blob null,
    primary key ("RequestID", "ContentID")
);

create index "mbttutorial_xs_repeatability_log_1_0_client_id_index" on "mbttutorial_xs_repeatability_log_1_0" ("ClientID");

create index "mbttutorial_xs_repeatability_log_1_0_creation_time_index" on "mbttutorial_xs_repeatability_log_1_0" ("CreationTime");
